on:
  pull_request:
  push:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: xmake-io/github-action-setup-xmake@v1
      
      - run: |
          xmake repo -u

      - run: |
          xmake f -a x64 -m release -p windows -v -y --build_type=server

      - run: |
          xmake -w -y

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-windows-server-x64-${{ github.sha }}
          path: |
            bin/
      
      - run: |
          xmake f -a x64 -m release -p windows -v -y --build_type=client

      - run: |
          xmake -w -y

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-windows-client-x64-${{ github.sha }}
          path: |
            bin/